#  run docker compose command
#  docker-compose -f docker-compose.dev.yml up

version: '3'

services:

  backend:
    container_name: backend-realcheck
    build: 
      context: ./backend
      dockerfile: prod-backend.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - ganache

  frontend:
    container_name: frontend-realcheck
    build:
      context: ./frontend
      dockerfile: dev-frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
